---
# Ensure the system package manager is updated
- name: Update apt cache
  apt:
    update_cache: yes

# Install Java 17
- name: Install Java 17
  apt:
    name: openjdk-17-jdk
    state: present

# Verify Java installation
- name: Verify Java installation
  command: java -version
  register: java_version_output
  ignore_errors: yes

# Install Git
- name: Install Git
  apt:
    name: git
    state: present

# Verify Git installation
- name: Verify Git installation
  command: git --version
  register: git_version_output
  ignore_errors: yes

