apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-deployment
  labels:
    app: ivolve-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ivolve-app
  template:
    metadata:
      labels:
        app: ivolve-app
    spec:
      containers:
        - name: ivolve-app
          image: ahmedmahmood44/ivolve-app:latest
          ports:
            - containerPort: 8081
       
