apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-deployment
  labels:
    app: ivolve-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ivolve-app
  template:
    metadata:
      labels:
        app: ivolve-app
    spec:
      containers:
        - name: ivolve-app
          image: your-docker-image:latest # Replace with your Docker image
          ports:
            - containerPort: 8081
       
---
apiVersion: v1
kind: Service
metadata:
  name: ivolve-service
spec:
  type: LoadBalancer
  selector:
    app: ivolve-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
