---
- name: Install required dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - gnupg
    - postgresql
    - postgresql-contrib
  ignore_errors: yes

- name: Ensure PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes


- name: Change postgres user password
  become: yes
  become_user: postgres
  postgresql_user:
    name: postgres
    password: "postgres"



- name: Create SonarQube database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    state: present

- name: Create SonarQube database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ postgresql_db }}"
    owner: "{{ postgresql_user }}"
    encoding: UTF8
    state: present

- name: Allow SonarQube user to access the database
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ postgresql_db }}"
    role: "{{ postgresql_user }}"
    privs: ALL
    type: database
  

- name: Configure pg_hba.conf for SonarQube
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: "0644"
  notify: Restart PostgreSQL

